
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: mm
      POSTGRES_PASSWORD: mm
      POSTGRES_DB: mm
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  api:
    build: ./api
    depends_on: [db]
    environment:
      DATABASE_URL: postgresql+asyncpg://mm:mm@db:5432/mm
      CORS_ORIGIN: http://localhost:5173
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  web:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    depends_on:
      - api
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app
      - /app/node_modules    # <-- add this line
    command: ["npm","run","dev","--","--host"]


volumes:
  dbdata:
